### ISSUE TITLE
Reset option for manual registration

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#119]
I set the Registration Box Size too small initially and had to click out of the tab and back again

**Comment by paskino** [comment]
Probably add a button "cancel" to stop the registration beside the "Confirm registration" one
![image](https://user-images.githubusercontent.com/14138589/195385194-81e4f89b-d1ea-4531-a089-2f2fec9f1393.png)

**Comment by lauramurgatroyd** [comment]
cancel should return the translations to what they had initially
