### ISSUE TITLE
Adjust range of colourmap for vectors

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#120]
Once #122 is done, it would be nice to be able to show only a range of vectors.

This requires to add a control for the vector size.

**Comment by paskino** [comment]
Trying to address this issue I started to calculate the magnitude of the displacement vectors in the magma dataset with the original pointcloud. While the color bar shows values between 23 and 1160, if I calculate the magnitude of the vectors I get something between 0 and 34.  

![image](https://user-images.githubusercontent.com/14138589/192895475-d4a4b205-c753-4386-93a6-250e672534f4.png)

Now, the 0 is an error, but the 34 is more plausible with the data, of which an extract you can see below
```
3312	1058	772	630	0	0.0727663	22.141082	3.691297	-0.049734
3313	1058	788	630	0	0.100433	19.475136	4.965291	-0.681700
3314	1058	804	630	0	0.0459249	18.623864	6.109452	0.049435
3315	1058	820	630	0	0.0233355	19.246701	6.170582	0.112837
3316	1058	836	630	0	0.0425954	19.837693	6.709418	-0.030388
3317	1058	852	630	0	0.0559498	19.590971	7.312339	-0.437918
3318	1058	868	630	0	0.0806104	20.092764	7.316818	-0.510127
3319	1058	884	630	0	0.0794032	20.230260	7.501356	-0.649580
```

What is the color bar referring to?

**Comment by paskino** [comment]
the color bar was showing the square of the magnitude.
