### ISSUE TITLE
App crashes if DVC run name not changed after run fails

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#143]
I tried to set up a run but my input was wrong. Changed my input and it had a command line error that the run name already existed and now the app is crashing

**Comment by paskino** [comment]
did you click **run**?

**Comment by paskino** [comment]
I guess, clicking RUN should disable the run button which will be re-enabled by setting a new name.

**Comment by lauramurgatroyd** [comment]
the user might not realise that's why its disabled, I would prefer an error message

**Comment by paskino** [comment]
The app shouldn't run if a run name already exists

**Comment by paskino** [comment]
After (not so) thorough investigation @lauramurgatroyd and I didn't manage to reproduce the error.

**Comment by lauramurgatroyd** [comment]
This morning I have reproduced this error many times. Here's an example of how you can reproduce it:

- Make a small pointcloud with subvolume size 5:
![image](https://user-images.githubusercontent.com/60604372/204258492-1136627d-35af-4106-b43b-6ce846d98d71.png)

- Apply these settings:
![image](https://user-images.githubusercontent.com/60604372/204258702-50c67c93-4305-4261-8598-fb9048599de0.png)

- You'll get an error message:
![image](https://user-images.githubusercontent.com/60604372/204258827-22315762-aef3-4f79-a3d7-32d48663bd55.png)

- Apply these settings and keep run name the same:
![image](https://user-images.githubusercontent.com/60604372/204258911-4414e6b7-0311-48a6-8ad7-b0db408576ac.png)

- Everything crashes!

![image](https://user-images.githubusercontent.com/60604372/204259016-92510a77-09e0-4165-a4b1-3dfa942dd6cb.png)

**Comment by lauramurgatroyd** [comment]
Note: the reason I get the "Failed to create pointcloud" error is because I am running on a cropped dataset with only 6 slices and the size of my pointcloud is bigger than the size in the slicing direction (i.e. 6)

**Comment by paskino** [comment]
I did the same and got the same error without the cropped dataset. As you point out in a small mask there may not be any point in the pointcloud. That's what trips the process.
