### ISSUE TITLE
Update docs for December training

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#146]
# Installation
https://github.com/TomographicImaging/iDVC/blob/master/docs/source/installation.rst
- [ ] update instructions should have latest version number
- [ ] After https://github.com/TomographicImaging/iDVC/issues/150 should describe how to use the environment.yaml file
- add conda pack instructions?

# DVC Run
- [x] Add info and tooltip on "All points button"
- [x] Describe the bulk mode as it changed behaviour
 https://github.com/TomographicImaging/iDVC/blob/master/docs/source/dvc_steps.rst#running-the-dvc-analysis

# DVC Results
- [x] Update to add some info and screenshots of new vectors with scaling
- [x] needs to reference to the new input interface, with vector ranges
https://github.com/TomographicImaging/iDVC/blob/master/docs/source/results.rst#displacement-vectors

**Comment by paskino** [comment]
## Installation
After #150 should describe how to use the `environment.yaml` file

## DVC Run
 also the `bulk` mode needs to be re-edited, as it changed behaviour

## DVC Results
needs to reference to the new input interface, with vector ranges
