### ISSUE TITLE
Whenever I run a bulk run it fails

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#156]
![image](https://user-images.githubusercontent.com/60604372/204277715-883449cc-56f3-45be-b098-398e67e4a0fa.png)

Then I changed the run name and some parameters
![image](https://user-images.githubusercontent.com/60604372/204277872-621497d5-e645-4895-a201-5ebcf183b61d.png)

I get this error:

> 'vtkCommonDataModelPython.vtkPolyData' object has no attribute 'SetOrientation'

**Comment by lauramurgatroyd** [comment]
Not able to replicate this any more

**Comment by paskino** [comment]
Potentially these lines are the origin of the error above, in particular line 3108

https://github.com/TomographicImaging/iDVC/blob/66db593719f67a0d26d7d0e6885616880bc878e0/src/idvc/dvc_interface.py#L3104-L3109

In fact `self.pointCloud` should be an instance of `cilRegularPointCloudToPolyData` 

https://github.com/TomographicImaging/iDVC/blob/66db593719f67a0d26d7d0e6885616880bc878e0/src/idvc/dvc_interface.py#L2888-L2893

while after the lines above it is a `vtkPolyData` (I'd say), so it misses the method `SetOrientation`.
```python
pointcloud = self.polydata_masker.GetOutputDataObject(0)
```

I'd say that we should remove line 3108 and just return `False`.
