### ISSUE TITLE
Import mesh and use nodes as pointcloud

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#168]
Avizo can export as abaqus input

Could have dropdown of supported formats

**Comment by paskino** [comment]
Info on [abaqus inp file](https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.5/books/gss/default.htm?startat=ch02s02.html)

**Comment by DanicaSTFC** [comment]
Refer to example data file for the nodes (see shared folder)

**Comment by DanicaSTFC** [comment]
Some interesting solution in https://stackoverflow.com/questions/75572698/how-to-load-and-inspect-a-gmsh-mesh-msh-file
