### ISSUE TITLE
Add ability to set OMP_NUM_THREADS to the settings

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#171]
The default value is not sufficient.

> The actual calculations were especially slow , by default it is using number of threads equal to all cores (40 threads) and this was severely slowing the calculation to about 1 point per second. 
> Setting the OMP_NUM_THREADS environment variable in the host environment allowed the dvc calculation to run much faster  
> 
> With 1 thread it would calculate about 7 points per second (default overlap/points/shape) 
> With 8 threads , about 15 
> With 16 threads , about 19 points per second 
> With 32 threads, about 17 
> With 39 threads, about 17
> With 40 threads, about 1  !!

**Comment by paskino** [comment]
Probably add to the Run DVC panel:

1. a checkbox to enable setting the number of threads
2. find the number of cpus available (`import multiprocessing ; cpus = multiprocessing.get_cpu_count()`)

Suggestion about the number of threads to use

```
if { $nproc > 16} {

    setenv    OMP_NUM_THREADS 16

} elseif { $nproc > 8 } {

    setenv    OMP_NUM_THREADS 8

} elseif { $nproc > 4 } {

    setenv OMP_NUM_THREADS 4

} else {

    setenv OMP_NUM_THREADS 1

}
```

**Comment by paskino** [comment]
Possibly this can be done by changing the environment for the QProcess by setting up a [`QProcessEnviroment`](https://www.qtcentre.org/threads/38289-Altering-QProcess-environment)

See also https://www.qtcentre.org/threads/38289-Altering-QProcess-environment
