### ISSUE TITLE
Registration box becomes opaque after pressing 's'

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#179]
can press 'w' to change it back to wireframe, but this should happen automatically

**Comment by lauramurgatroyd** [comment]
See https://github.com/vais-ral/CILViewer/issues/331 - having a toolbar with settings means they will no longer use the 's' keypress

**Comment by paskino** [comment]
Work is in progress in removing the key presses and adding a tool bar in the viewer.

**Comment by lauramurgatroyd** [comment]
Another problem is although it changes to wireframe when 'w' is pressed, this also changes the vectors on the 3D view to wrireframe as well, which we don't want as the arrows are difficult to see in wireframe

**Comment by paskino** [comment]
We should intercept the keypress `w` and `s` and consume it.
