### ISSUE TITLE
Issue with display of results graphs, especially in bulk run

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#200]
There is a large space underneath where the graphs are displayed.

When there are a lot of graphs, they appear very small and a lot of text overlaps.
![image](https://github.com/TomographicImaging/iDVC/assets/60604372/61fd0863-77d5-4749-80eb-c3a4b04379c5)

**Comment by DanicaSTFC** [comment]
Meeting with Brian 09/05/2024: The bulk run will not be used in the workshop so this should be low priority for the workshop
