### ISSUE TITLE
Add automatic registration to iDVC

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#205]
This will use the algorithm generated by @DanicaSTFC 

It will need to be added by running this algorithm in a Worker thread (https://github.com/TomographicImaging/eqt/blob/main/eqt/threading/QtThreading.py)
when the user starts the registration on the Image registration panel

"Start Registration" button trigger is here: https://github.com/TomographicImaging/iDVC/blob/ea87844d38d161a18d5217478856790006feb505/src/idvc/dvc_interface.py#L1160

This calls this method: https://github.com/TomographicImaging/iDVC/blob/ea87844d38d161a18d5217478856790006feb505/src/idvc/dvc_interface.py#L1578
Which creates a cropped version of the dataset at full resolution, of the registration box size *3 in each dimension.
If this size of data is useful, this cropping could be kept and passed to the algorithm.
This can be retrieved by calling `getRegistrationVOIs` which returns [data1, data2] which is the cropped reference volume and correlate volume respectively. You may need to convert the format of these data from vtk to numpy.

I believe it is before or within `completeRegistration` that you will want to launch the automatic registration code: https://github.com/TomographicImaging/iDVC/blob/ea87844d38d161a18d5217478856790006feb505/src/idvc/dvc_interface.py#L1635
You will want to run in a worker which can take the data from `getRegistrationVOIs `

Perhaps it's best to make a new method dedicated to launching your worker, and when your worker is complete it calls `completeRegistration`. So that would mean that all existing calls to `completeRegistration` would need to be replaced with 
a call to your method.

Please note, I have written this advice based on a quick look at the code, and can dedicate more time later to look in more detail, so please read with caution!

**Comment by lauramurgatroyd** [comment]
The automatic registration will output a translation. This will need to be updated on the GUI.
The place where the translations are shown is in these widgets (i,e, this is where the widgets are first created):
https://github.com/TomographicImaging/iDVC/blob/ea87844d38d161a18d5217478856790006feb505/src/idvc/dvc_interface.py#L1119-L1153

**Comment by DanicaSTFC** [comment]
@lauramurgatroyd 

It doesn't look like `getRegistrationVOIs` returns the data as registration box size *3 in each dimension. The cropping is hard coded and it is fixed to 1 time the extent size. Where is it done?

**Comment by lauramurgatroyd** [comment]
This line should be creating an extent that is registration box size *3 in each dimension and centred on the selected point 0:
https://github.com/TomographicImaging/iDVC/blob/ea87844d38d161a18d5217478856790006feb505/src/idvc/dvc_interface.py#L1708

Have you found the data returned from getRegistrationVOIs is a different size?

**Comment by lauramurgatroyd** [comment]
self.unsampled_ref_image_data and self.unsampled_corr_image_data are the full resolution data, cropped only on the Z axis to 3*registration box size.
For the x and y axis we only crop when it comes to displaying on the viewer and that crops to just the registration box size

**Comment by lauramurgatroyd** [comment]
Related issue in viewer: https://github.com/vais-ral/CILViewer/issues/129 this is why we only crop on Z axis at the moment

**Comment by DanicaSTFC** [comment]
> This line should be creating an extent that is registration box size *3 in each dimension and centred on the selected point 0:
> 
> https://github.com/TomographicImaging/iDVC/blob/ea87844d38d161a18d5217478856790006feb505/src/idvc/dvc_interface.py#L1708
> 
> Have you found the data returned from getRegistrationVOIs is a different size?

extent is 1 time the box size

**Comment by DanicaSTFC** [comment]
> self.unsampled_ref_image_data and self.unsampled_corr_image_data are the full resolution data, cropped only on the Z axis to 3*registration box size. For the x and y axis we only crop when it comes to displaying on the viewer and that crops to just the registration box size

I will crop the numpy arrays in x and y locally in idvc

**Comment by DanicaSTFC** [comment]
I opened a new issue #212 to clarifiy the difference between the 3D shift and the registration box size. I can use the 3 * registration box size in the automatic registration. However, this will need to be addressed in the viewer as currently the viewer is limited to 1 time the size.

**Comment by DanicaSTFC** [comment]
@lauramurgatroyd , I am finding it hard to  order the actions between the manual and automatic registration to synchronize the viewer. I have fixed it a little bit but would be great if you could add the docstrings to the following methods please:

 `self.manual_registration`
 `self.updatePoint0Display()`
 `self.translateImages()`
`self.reg_viewer_update(type = 'starting registration')`
`self.centerOnPointZero() `
`OnStartStopRegistrationPushed`
`LoadImagesAndCompleteRegistration`

and also a note on `self.translate.SetTranslation(...)`

Thanks!

**Comment by lauramurgatroyd** [comment]
`self.translate.SetTranslation` is a VTK method.
`self.translate` is a `vtk.vtkImageTranslateExtent()` object
https://vtk.org/doc/nightly/html/classvtkImageTranslateExtent.html#ad5c38b3f3aa05a58be3ef020712de0e6

**Comment by lauramurgatroyd** [comment]
Docstrings have been added in https://github.com/TomographicImaging/iDVC/pull/214

**Comment by DanicaSTFC** [comment]
> Docstrings have been added in #214

Thank you @lauramurgatroyd

**Comment by lauramurgatroyd** [comment]
> > self.unsampled_ref_image_data and self.unsampled_corr_image_data are the full resolution data, cropped only on the Z axis to 3*registration box size. For the x and y axis we only crop when it comes to displaying on the viewer and that crops to just the registration box size
> 
> I will crop the numpy arrays in x and y locally in idvc

If you want to crop data that is already in memory using VTK I think you would want to use:
https://vtk.org/doc/nightly/html/classvtkExtractVOI.html#details
There is a C++ example which is very similar to the python: https://examples.vtk.org/site/Cxx/ImageData/ExtractVOI/
Or an example already in the idvc code: 
https://github.com/TomographicImaging/iDVC/blob/b9a10f3e8f2f037079dcbc11d57888b10b500fd8/src/idvc/dvc_interface.py#L1761
