### ISSUE TITLE
Terminal outputs "Unhandled event" when keys are pressed

### ISSUE THREAD

**Issue by DanicaSTFC** [TomographicImaging/iDVC#220]
When I run the app the terminal shows
- "Unhandled event w" when "w" is pressed in the 3D viewer.
Can we change this so this is not printed? I noticed this sentence is printed for most keys pressed in the 3D viewer.

When I pressed "q" on the 3D viewer the app stopped responding. Is this something similar to the w behaviour we could avoid?

_Originally posted by @DanicaSTFC in https://github.com/TomographicImaging/iDVC/pull/218#pullrequestreview-1822060923_

**Comment by paskino** [comment]
This is a viewer problem. @DanicaSTFC please open an issue there.

**Comment by DanicaSTFC** [comment]
Opened issue here https://github.com/vais-ral/CILViewer/issues/376#issue-2118570393
