### ISSUE TITLE
The manual registration not working well

### ISSUE THREAD

**Issue by DanicaSTFC** [TomographicImaging/iDVC#280]
From Brian: Also, I think I’ve seen the problem with modifying the registration manually. The 2D display is not showing the difference image, just the plain data image. When you use the j/n/b/m keys, the numbers in Translate change, but you don’t see the effect in the 2D view plane.

12/06/2024 The problem should be that in the previous environment vtk was  8.1.2. In the new environment this is vtk 9.3.0. I confirmed this by installing a new environment and fixing vtk 8.1.2. The manual registration works well.

**Comment by paskino** [comment]
Installing with `conda env create -n idvc_vtk9_reg -f recipe\dev_environment.yml` I get `ccpi-viewer 22.4.0` and hence `vtk` 8.
