### ISSUE TITLE
If bulk run fails to create pointcloud, then all future runs fail 

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#35]
We get an error message: "'vtkCommonDataModelPython.vtkPolyData' object has no attribute 'SetOrientation'"

**Comment by paskino** [comment]
this could be handled when fixing #37

**Comment by lauramurgatroyd** [comment]
after addressing #90 we won't have the bulk run generate any pointclouds so this won't be relevant
