### ISSUE TITLE
Can't minimise app during run

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#38]
Minimising the run progress window only minimises this, and you can't minimise the app

**Comment by paskino** [comment]
That's because the progress bar is a modal window.

If we want to be able to work with the main window during run we need to disable all things that may break the behaviour.

So far so good?

**Comment by lauramurgatroyd** [comment]
we need to prevent progress window from being able to be minimised

**Comment by paskino** [comment]
This requires to set the windows flags https://doc.qt.io/qt-6/qt.html#WindowType-enum

Probably this means that on the creation of the ProgressBar we need to set the flags to 
```
Qt::CustomizeWindowHint | Qt::WindowTitleHint | Qt::WindowCloseButtonHint
```
https://github.com/TomographicImaging/iDVC/blob/7f4a0c3093ba73a8e720f769f103a2bd3d0086e7/src/idvc/dvc_interface.py#L790

while it's now set to `QtCore.Qt.Window`
