### ISSUE TITLE
Do vectors get added to the world in image coordinates or world coordinates?

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#39]
The txt file that the displacements are read from has the coords in image coords.
We need to convert to world coords to display them.
We need to check that this actually happens.

**Comment by paskino** [comment]
The answer I suppose is that they get added in the world, not in image coordinates

**Comment by paskino** [comment]
What needs investigating here @lauramurgatroyd ? 
Actors are placed in the world. However, the DVC command does have no clue of image spacing, so for it world and image coordinates match.

I'm assuming we are already doing the right job as the vectors get painted in the right place in the downsampled image?
