### ISSUE TITLE
Registration panel lets you select registration box larger than the image size

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#63]
This then crashes when you go to register the image

**Comment by paskino** [comment]
It's not too critical with large dataset, with small images this may happen.

**Comment by lauramurgatroyd** [comment]
Noticed this issue again today @paskino - it is a problem especially if you have an image with fewer slices on the z direction - it is easy to set a registration box bigger than the size along the z direction without noticing and cause a crash

**Comment by paskino** [comment]
What is the logic with which we decide on the size of the registration box?

**Comment by lauramurgatroyd** [comment]
The PR which was merged makes sure that the box can't be bigger than any dimension. Then it checks which slice you are on and makes sure you are not overlapping the edge of the image in the direction you are slicing
