### ISSUE TITLE
With master of iDVC and CILViewer, image registration crashes

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#74]
- box for image registration does not display on interface
- as soon as you try to navigate in image registration the app crashes with error:

> 2021-11-12 15:44:06.704 (  77.580s) [                ]vtkStreamingDemandDrive:878    ERR| vtkStreamingDemandDrivenPipeline (0000021A901D32E0): The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0000021ACD084900) is 609 767 458 616 556 556, which is outside the whole extent 610 767 458 616 477 635.
> 2021-11-12 15:44:06.704 (  77.580s) [                ] vtkTrivialProducer.cxx:241    ERR| vtkTrivialProducer (0000021ACD084900): This data object does not contain the requested extent.
> 2021-11-12 15:44:06.705 (  77.580s) [                ]       vtkImageData.cxx:1520   ERR| vtkImageData (0000021AEE707630): GetScalarPointer: Pixel (609, 458, 556) not in memory.
>  Current extent= (610, 767, 458, 616, 556, 556)

it's clearly something to do with the coordinates of the extents etc.

To install current master of iDVC and CILViewer and replicate the issue, use:

`conda install idvc -c murgadroid -c paskino -c ccpi -c conda-forge`

This should install iDVC and CILViewer from the murgadroid channel and vtk9

**Comment by paskino** [comment]
> The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(0000021ACD084900) is 609 767 458 616 556 556, which is outside the whole extent 610 767 458 616 477 635.

So the question is why it gets 609 rather than 610

**Comment by lauramurgatroyd** [comment]
The problem occurs when you press one of the keys in too quick succession. The subtraction + translation occurs in a worker, so what happens is it can begin doing a new subtraction and translation in the middle of it doing a previous one and it gets confused!

**Comment by lauramurgatroyd** [comment]
We can fix this by not translating and subtracting in a worker, I tried it and it seems fine

**Comment by paskino** [comment]
Are you sure this is the problem? I believe you, but it looked to be a wrong extent
