### ISSUE TITLE
With vtk9 the pointcloud outline doesn't display and nor does the image registration box

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#77]

**Comment by lauramurgatroyd** [comment]
These are both opaque 3D shapes which we clip. There is no issue displaying the shapes that we display as a wireframe

**Comment by lauramurgatroyd** [comment]
Note the spheres work:

![image](https://user-images.githubusercontent.com/60604372/146365676-4d0f0e34-9606-442a-b655-172c7bb89fc7.png)

**Comment by lauramurgatroyd** [comment]
Both the registration box and pointcloud cubes are created using a `vtk.vtkCubeSource` - this is where the issue lies with vtk9 it seems as we can see other shapes

**Comment by lauramurgatroyd** [comment]
If we turn off the planeclipping it appears (although obviously not as an outline as we would like:
![image](https://user-images.githubusercontent.com/60604372/146366977-85d6f911-5790-46eb-8762-fafff866acfd.png)

**Comment by lauramurgatroyd** [comment]
We also need to establish whether this is an issue due to using vtk9 or due to other updates in the viewer such as using the imageSlice

**Comment by paskino** [comment]
> Both the registration box and pointcloud cubes are created using a `vtk.vtkCubeSource` - this is where the issue lies with vtk9 it seems as we can see other shapes

You mean that we can see the subvolumes if they are spheres? I'll try

**Comment by paskino** [comment]
Actually that seems to be true.

**Comment by lauramurgatroyd** [comment]
I tested the app with the latest viewer code (from master) but with vtk8 instead of 9 and the squares were visible, so it's an issue with vtk9 not with using the vtkImageSlice

**Comment by lauramurgatroyd** [comment]
This means until we have fixed the issue, we could release the viewer with the requirement vtk 8.1.2 or greater, and then for idvc require the version to be 8.1.2

**Comment by paskino** [comment]
Apparently in VTK >= 9.1 we need to use the following additional `vtkProperty` of the actor.

```
actor.GetProperty().SetRepresentationToWireframe()
actor.GetProperty().SetRenderLinesAsTubes(True)
```

**Comment by paskino** [comment]
The suggested [change ](https://github.com/TomographicImaging/iDVC/tree/box_clipping_actor) above seems to work with VTK 9.2 

![image](https://github.com/TomographicImaging/iDVC/assets/14138589/4c0f6768-8b39-4743-a403-8d682a3ab83e)
